"""
Script para hacer backup completo de la base de datos PostgreSQL
Usa las mismas credenciales de .env que la aplicación
"""
import os
import subprocess
from datetime import datetime
from pathlib import Path

def backup_database():
    """Exporta la base de datos completa usando pg_dump"""
    
    # Configuración
    backup_dir = Path(r"D:\0.A. Proyectos\0.0. BackUp\BackUp 1.1. Control de Acceso Visitantes\database_backup")
    backup_dir.mkdir(parents=True, exist_ok=True)
    
    # Nombre del archivo con timestamp
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    backup_file = backup_dir / f"control_visitantes_backup_{timestamp}.sql"
    
    # Credenciales de PostgreSQL
    db_config = {
        'host': 'localhost',
        'port': '5432',
        'user': 'postgres',
        'password': 'G3st0radm$2025.@',
        'database': 'control_visitantes'
    }
    
    # Path a pg_dump
    pg_dump_path = r"C:\Program Files\PostgreSQL\18\bin\pg_dump.exe"
    
    # Comando pg_dump
    cmd = [
        pg_dump_path,
        '-h', db_config['host'],
        '-p', db_config['port'],
        '-U', db_config['user'],
        '-d', db_config['database'],
        '-F', 'p',  # Formato plain SQL
        '--inserts',  # Usar INSERT en vez de COPY
        '--column-inserts',  # Incluir nombres de columnas
        '-f', str(backup_file)
    ]
    
    # Configurar variable de entorno para la contraseña
    env = os.environ.copy()
    env['PGPASSWORD'] = db_config['password']
    
    try:
        print(f"🔄 Iniciando backup de la base de datos...")
        print(f"📦 Base de datos: {db_config['database']}")
        
        # Ejecutar pg_dump
        result = subprocess.run(
            cmd,
            env=env,
            capture_output=True,
            text=True,
            timeout=300  # 5 minutos máximo
        )
        
        if result.returncode == 0:
            # Verificar que el archivo se creó y tiene contenido
            if backup_file.exists() and backup_file.stat().st_size > 0:
                size_mb = backup_file.stat().st_size / (1024 * 1024)
                print(f"\n✅ BACKUP COMPLETADO EXITOSAMENTE")
                print(f"📁 Archivo: {backup_file}")
                print(f"📊 Tamaño: {size_mb:.2f} MB")
                print(f"🕐 Fecha: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
                return True
            else:
                print(f"\n⚠️ El archivo de backup está vacío o no se creó")
                return False
        else:
            print(f"\n❌ Error en pg_dump:")
            print(f"STDOUT: {result.stdout}")
            print(f"STDERR: {result.stderr}")
            
            # Intentar método alternativo con psycopg
            print(f"\n🔄 Intentando método alternativo con psycopg...")
            return backup_with_psycopg(backup_file, db_config)
            
    except subprocess.TimeoutExpired:
        print(f"\n❌ Timeout: El backup tomó más de 5 minutos")
        return False
    except Exception as e:
        print(f"\n❌ Error inesperado: {e}")
        return False


def backup_with_psycopg(backup_file, db_config):
    """Método alternativo: usar psycopg para obtener el schema y datos"""
    try:
        import psycopg
        from psycopg.rows import dict_row
        
        # Usar el mismo connection string que usa la aplicación (sin el +psycopg)
        # La contraseña tiene caracteres especiales, usando URL encoding
        from urllib.parse import quote_plus
        
        password_encoded = quote_plus(db_config['password'])
        conn_string = f"postgresql://{db_config['user']}:{password_encoded}@{db_config['host']}:{db_config['port']}/{db_config['database']}"
        
        print(f"   └─ Intentando conexión con psycopg...")
        
        with psycopg.connect(conn_string) as conn:
            with open(backup_file, 'w', encoding='utf-8') as f:
                # Header
                f.write("-- PostgreSQL Database Backup\n")
                f.write(f"-- Database: {db_config['database']}\n")
                f.write(f"-- Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write("-- Generated by backup_database.py\n\n")
                f.write("SET statement_timeout = 0;\n")
                f.write("SET lock_timeout = 0;\n")
                f.write("SET client_encoding = 'UTF8';\n\n")
                
                # Obtener lista de tablas
                with conn.cursor() as cur:
                    cur.execute("""
                        SELECT tablename 
                        FROM pg_tables 
                        WHERE schemaname = 'public'
                        ORDER BY tablename
                    """)
                    tables = [row[0] for row in cur.fetchall()]
                
                print(f"📋 Tablas encontradas: {len(tables)}")
                
                for table in tables:
                    print(f"   └─ Exportando tabla: {table}")
                    
                    # Schema de la tabla
                    with conn.cursor() as cur:
                        cur.execute(f"""
                            SELECT 
                                'CREATE TABLE ' || tablename || E' (\n' ||
                                string_agg(column_def, E',\n') ||
                                E'\n);' as create_script
                            FROM (
                                SELECT 
                                    tablename,
                                    '    ' || column_name || ' ' || 
                                    data_type ||
                                    CASE 
                                        WHEN character_maximum_length IS NOT NULL 
                                        THEN '(' || character_maximum_length || ')'
                                        ELSE ''
                                    END ||
                                    CASE 
                                        WHEN is_nullable = 'NO' THEN ' NOT NULL'
                                        ELSE ''
                                    END as column_def
                                FROM information_schema.columns
                                WHERE table_schema = 'public' AND table_name = '{table}'
                                ORDER BY ordinal_position
                            ) t
                            GROUP BY tablename;
                        """)
                        result = cur.fetchone()
                        if result:
                            f.write(f"\n-- Table: {table}\n")
                            f.write(f"DROP TABLE IF EXISTS {table} CASCADE;\n")
                            f.write(f"{result[0]}\n\n")
                    
                    # Datos de la tabla
                    with conn.cursor(row_factory=dict_row) as cur:
                        cur.execute(f'SELECT * FROM "{table}"')
                        rows = cur.fetchall()
                        
                        if rows:
                            f.write(f"-- Data for table: {table} ({len(rows)} rows)\n")
                            
                            for row in rows:
                                columns = ', '.join(row.keys())
                                values = []
                                for val in row.values():
                                    if val is None:
                                        values.append('NULL')
                                    elif isinstance(val, str):
                                        # Escapar comillas simples
                                        escaped = val.replace("'", "''")
                                        values.append(f"'{escaped}'")
                                    elif isinstance(val, (int, float)):
                                        values.append(str(val))
                                    else:
                                        values.append(f"'{str(val)}'")
                                
                                values_str = ', '.join(values)
                                f.write(f"INSERT INTO {table} ({columns}) VALUES ({values_str});\n")
                            
                            f.write("\n")
        
        if backup_file.exists() and backup_file.stat().st_size > 0:
            size_mb = backup_file.stat().st_size / (1024 * 1024)
            print(f"\n✅ BACKUP COMPLETADO CON MÉTODO ALTERNATIVO")
            print(f"📁 Archivo: {backup_file}")
            print(f"📊 Tamaño: {size_mb:.2f} MB")
            return True
        else:
            print(f"\n❌ El backup alternativo falló")
            return False
            
    except Exception as e:
        print(f"\n❌ Error en backup alternativo: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == '__main__':
    print("=" * 70)
    print("BACKUP DE BASE DE DATOS - Sistema Control de Visitantes")
    print("=" * 70)
    print()
    
    success = backup_database()
    
    if success:
        print("\n✅ Proceso completado exitosamente")
        exit(0)
    else:
        print("\n❌ El backup no se completó correctamente")
        exit(1)
